# lobby
VALIDATE_PLAYER_NAME = 0
PLAYER_NAME_AND_READY_STATUS = 1
ADD_BOT = 2
REMOVE_BOT = 3
START_GAME = 4
ADD_ROUND = 5
REMOVE_ROUND = 6
NAME_VALIDATION_RESPONSE = 7
# game
ACTIVE_PLAYERS = 8
STARTING_WALLS_AND_PLAYERS = 9
PLAYERS_AND_BULLETS = 10
END_GAME = 11
PLAYER_INSTRUCTIONS = 12


