
# client lobby
SEND_TO_SERVER_NAME_FOR_VALIDATION = 0
SEND_TO_SERVER_PLAYER_NAME_AND_READY_STATUS = 1
SEND_TO_SERVER_ADD_BOT = 2
SEND_TO_SERVER_REMOVE_BOT = 3
SEND_TO_SERVER_START_SIGN = 4
SEND_TO_SERVER_ADD_ROUND = 5
SEND_TO_SERVER_REMOVE_ROUND = 6

RECIVE_PLAYERS_FROM_SERVER = 0
RECIVE_GAME_START_SIGN_FROM_SERVER = 1

# client game


# server